name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: macos-15

    strategy:
      matrix:
        xcode: ["26.0"]

    name: Build (Xcode ${{ matrix.xcode }})

    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Skip macro validation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Build
        run: xcodebuild -scheme olleh -sdk macosx -destination "generic/platform=macOS,name=Any Mac"
